### ISSUE TITLE
Mensagem não processada no ViewController

### ISSUE THREAD

**Issue by elton-santana** [Valbrand/tibei#2]
Vossa Santidade,

Então, quando dou `registerResponder` varias vezes sem dar `unregister` chegam varias mensagens no meu view controller, ainda que o tibei só da print em um payload.

Minhas telas estão organizadas assim, o fluxo se divide para abrir um serviço ou se conectar a um ja existente.

![screen shot 2017-01-16 at 14 05 14](https://cloud.githubusercontent.com/assets/22280044/21992765/7d8391bc-dbf6-11e6-8ae2-75b3c31bb79e.png)

Antes de sair eu dou `unregister` no view controller anterior, nos dois casos (server e client).

![screen shot 2017-01-16 at 14 39 04](https://cloud.githubusercontent.com/assets/22280044/21993439/9aab30a8-dbf9-11e6-87e5-8f69abcee8e1.png)

E assim que chego no view controller de PrepareToPlay que é algo onde server e client passam eu dou `register` novamente.

![screen shot 2017-01-16 at 14 37 29](https://cloud.githubusercontent.com/assets/22280044/21993395/64a57bbc-dbf9-11e6-9574-1a5a7e319c05.png)

Agora o Tibei recebe o payload, mas o VC não processa.

![screen shot 2017-01-16 at 14 11 54](https://cloud.githubusercontent.com/assets/22280044/21993153/2d5f50ac-dbf8-11e6-960a-495723ba06e3.png)

O que observei é que quando não dou `unregister` e dou `register` em todos os VC, todos eles processam mensagens e, em alguns casos, processam mais do que deveria. Quando dou `unregister`, no VC seguinte é como não conseguisse dar mais `register`. Já que o payload chega mas o VC não processa.

**Comment by Valbrand** [comment]
Consertado no PR #4

**Comment by elton-santana** [comment]
Tudo ok
